# https://docs.docker.com/compose/compose-file/compose-file-v3/
---
version: '3.8'
    
services:
  nginx:
    image: nginx:latest
    ports: ["8080:80","9080:5000"]
    volumes:
    - type: bind
      source: "./../files"
      target: "/config"
      read_only: true
    command: [
      "/usr/sbin/nginx",
      "-c",
      "/config/nginx.conf",
    ]
...